name: ci

on:
  push:
  pull_request:

jobs:
  lint-and-dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          pip install ruff==0.6.9
          pip install dbt-core==1.8.7 dbt-postgres==1.8.2

      - name: Ruff
        run: ruff check .

      - name: dbt deps + parse
        working-directory: dbt/aqw
        run: |
          dbt deps
          dbt parse
